#! /bin/bash
sudo apt install -y cmake
sudo apt install -y tldr #tldr -u
sudo apt install -y tmux
sudo apt install -y gimp
sudo apt install -y ncdu
sudo apt install -y nvtop
sudo apt install -y ctop
sudo apt install -y fzf
sudo apt install -y tree
sudo apt install -y build-essential
sudo apt install -y python3 python3-pip python-is-python3

# export http_proxy="192.168.0.1:7890"
# export https_proxy="192.168.0.1:7890"
